# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d815289fa69acbb3a32989843e02aeb72bd1f1efe11dedf743ea8220e512413f2d7fa5daed771b16c4e23cea3ce00b3f1cc0b556de5420f318c81a899869b953

test:
  secret_key_base: 96658bf27e67693f0875337b8fa983c8cfc9554269102e5ecd756ae8ddab6c8f55267e4aafe8ff3b19118b62a7d95d4270b7f2ce3fbe5717e4c4641f6ce0acc8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
